apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: billingservice

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: billingservice
  labels:
    app: billingService
    service: billingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billingService
      service: billingservice
  template:
    metadata:
      labels:
        app: billingService
        service: billingservice
    spec:
      serviceAccountName: billingservice
      
      containers:
      - name: billingservice-container
        image: hhana982/billingservice:1.<version>
        ports:
        - containerPort: 8080
        
        env: 