apiVersion: v1
kind: Service
metadata:
  name: billingservice
  labels:
    app: billingService
    service: billingservice
spec:
  selector:
    app: billingService
    service: billingservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP