apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: billingservice-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: billingservice-db
  labels:
    app: billingService-db
    service: billingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billingService-db
      service: billingservice
  template:
    metadata:
      labels:
        app: billingService-db
        service: billingservice
    spec:
      serviceAccountName: billingservice-db
      volumes:
      - name: billingService-db-volume
        persistentVolumeClaim:
          claimName: billingService-db
      containers:
      - name: billingservice-db-container
        image: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql"
          name: billingService-db-volume
        env: 
        - name: POSTGRES_PASSWORD
          value: "password"