apiVersion: v1
kind: Service
metadata:
  name: billingservice-db
  labels:
    app: billingService-db
    service: billingservice
spec:
  selector:
    app: billingService-db
    service: billingservice
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP